name: data_lesson
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite: ^2.2.0+3
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  alert_dialog: ^1.0.1
  modal_bottom_sheet: ^2.1.2
  date_utils: ^0.2.0
  jiffy: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
